const CONFIG = {
const CONFIG = {
    titleWeb: "Ẩn danh",
    introTitle: 'Gửi bạn Mai béo',
    introDesc: `MÃI BÊN NHAU BẠN NHÁ(((:`,
    btnIntro: '^^HiHi^^',
    title: 'If you never had Friends, you never lived life',
    desc: 'Bạn là? ',
    btnYes: 'Mai Bún lèo D:',
    btnNo: 'Dương Quỳnh Mai D:',
    question: 'thi xong bao cả bọn đi ăn hây ((:',
    btnReply: 'gửi cho 7 đứa còn lại',
    reply: 'tất nhiên',
    mess: 'Ok chốt nhá',
    messDesc: 'chúc Mai Đỗ nv1 nha thi xong leo ctuong thôi bonus:https://gifft.me/3d#GgMclAIrTf5b3qx2hkdx',
    btnAccept: 'Okiiiii lun ',
